#!/usr/bin/env bash
# ghost-rebase.sh — replay ghost commit prompts through a different agent

set -euo pipefail

# shellcheck source=lib/ghost-common.sh
source "${GHOST_ROOT}/lib/ghost-common.sh"
# shellcheck source=lib/ghost-agents.sh
source "${GHOST_ROOT}/lib/ghost-agents.sh"

rebase_usage() {
  cat <<'EOF'
ghost rebase — replay ghost commit prompts through a different agent

Extracts the original prompts from every ghost commit in the specified
range, resets the branch to the base commit, then re-runs each prompt
in order using the configured agent and model.  The result is a brand-
new commit history built from the same intents but generated by a
different AI.

Usage:
  ghost rebase [--agent AGENT] [--model MODEL] <base>
  ghost rebase --help

Arguments:
  <base>          Base commit / revision to rebase from.
                  Everything between <base> and HEAD is replayed.
                  Examples: HEAD~3, abc1234, main

Options:
  --agent AGENT   Agent to use for replay (claude, gemini, codex, opencode)
                  Default: current GHOST_AGENT or claude
  --model MODEL   Model override for the agent
  --dry-run       Print the prompts that would be replayed, do not execute
  -h, --help      Show this help

Examples:
  # Re-run the last 3 ghost commits with Gemini
  ghost rebase --agent gemini HEAD~3

  # Re-run from a specific commit with a specific model
  ghost rebase --agent gemini --model gemini-2.5-pro HEAD~5

  # Preview what would be replayed without changing anything
  ghost rebase --dry-run HEAD~3

Notes:
  - The working tree must be clean before running ghost rebase.
  - Only ghost commits (those containing ghost-meta) are replayed.
    Plain git commits in the range are silently skipped.
  - This operation rewrites history. Do not use on commits that have
    already been pushed to a shared remote without coordinating with
    your team.
EOF
}

# _rebase_collect_prompts <base_commit>
# Prints one line per ghost commit in <base_commit>..HEAD (oldest first):
#   <hash> TAB <prompt>
_rebase_collect_prompts() {
  local base="$1"
  while IFS= read -r hash; do
    local body
    body="$(git log -1 --format=%B "$hash")"
    echo "$body" | grep -q "^${GHOST_META_MARKER}$" || continue
    local prompt
    prompt="$(echo "$body" | grep "^${GHOST_PROMPT_KEY}:" | sed "s/^${GHOST_PROMPT_KEY}: //" || true)"
    [ -n "$prompt" ] && printf '%s\t%s\n' "$hash" "$prompt"
  done < <(git log --reverse --format=%H "${base}..HEAD" 2>/dev/null)
}

cmd_rebase() {
  ghost_ensure_repo
  ghost_init_colors

  local agent="${GHOST_DEFAULT_AGENT}"
  local model=""
  local range=""
  local dry_run=0

  while [[ $# -gt 0 ]]; do
    case "$1" in
      --agent)
        shift
        agent="${1:?'--agent requires a value'}"
        shift
        ;;
      --model)
        shift
        model="${1:?'--model requires a value'}"
        shift
        ;;
      --dry-run)
        dry_run=1
        shift
        ;;
      help|-h|--help)
        rebase_usage
        exit 0
        ;;
      -*)
        gh_error "error: unknown option: $1"
        gh_error "Run 'ghost rebase --help' for usage."
        exit 1
        ;;
      *)
        if [ -n "$range" ]; then
          gh_error "error: unexpected argument: $1"
          exit 1
        fi
        range="$1"
        shift
        ;;
    esac
  done

  # ── Validate inputs ────────────────────────────────────────────────────────
  if [ -z "$range" ]; then
    gh_error "error: base commit required (e.g. HEAD~3)"
    rebase_usage
    exit 1
  fi

  if ! ghost_validate_agent "$agent"; then
    gh_error "error: unsupported agent: ${agent}"
    gh_error "  supported: ${GHOST_SUPPORTED_AGENTS[*]}"
    exit 1
  fi

  # Resolve model
  if [ -z "$model" ]; then
    model="$(ghost_default_model "$agent")"
  fi

  # Resolve base commit hash
  local base_commit
  if ! base_commit="$(git rev-parse --verify "${range}" 2>/dev/null)"; then
    gh_error "error: cannot resolve '${range}' to a commit"
    exit 1
  fi

  # ── Collect prompts ────────────────────────────────────────────────────────
  ghost_spinner_start "scanning ghost commits in range…"
  local raw_entries
  raw_entries="$(_rebase_collect_prompts "$base_commit")"
  ghost_spinner_stop

  if [ -z "$raw_entries" ]; then
    gh_label "  ghost: no ghost commits found between ${range} and HEAD. Nothing to replay."
    exit 0
  fi

  # Parse into parallel arrays (bash 3 compat — no associative arrays needed)
  local -a prompt_hashes=()
  local -a prompt_texts=()
  while IFS=$'\t' read -r h p; do
    prompt_hashes+=("$h")
    prompt_texts+=("$p")
  done <<< "$raw_entries"

  local total="${#prompt_texts[@]}"

  # ── Header ─────────────────────────────────────────────────────────────────
  printf "\n%b  ▸ ghost rebase-regen%b\n" "${GH_PINK}${GH_BOLD}" "${GH_RESET}"
  gh_kv "agent"   "${agent}"
  [ -n "$model" ] && gh_kv "model"  "${model}"
  gh_kv "base"    "$(git log -1 --format='%h %s' "${base_commit}")"
  gh_kv "commits" "${total}"
  [ "$dry_run" = "1" ] && gh_kv "mode" "dry-run"
  printf "\n"

  printf "%bprompts to replay:%b\n" "${GH_PURPLE}" "${GH_RESET}"
  local i
  for (( i=0; i<total; i++ )); do
    printf "  %b%d.%b %s\n" \
      "${GH_CYAN}" "$((i+1))" "${GH_RESET}" "${prompt_texts[$i]}"
  done
  printf "\n"

  if [ "$dry_run" = "1" ]; then
    gh_label "  ghost: dry-run complete. No changes made."
    exit 0
  fi

  # ── Check working tree is clean ────────────────────────────────────────────
  if ! git diff --quiet || ! git diff --cached --quiet; then
    gh_error "error: working tree has uncommitted changes."
    gh_error "  Stash or commit your changes before running ghost rebase."
    exit 1
  fi

  # ── Confirm (interactive only) ─────────────────────────────────────────────
  if [ -t 0 ] && [ -t 1 ]; then
    printf "%bThis will reset HEAD to %s and replay %d commit(s).%b\n" \
      "${GH_RED}" "${range}" "${total}" "${GH_RESET}"
    printf "%bThis rewrites history. Continue? [y/N] %b" "${GH_BOLD}" "${GH_RESET}"
    local answer
    read -r answer
    case "$answer" in
      y|Y|yes|YES) ;;
      *)
        gh_label "  ghost: aborted."
        exit 1
        ;;
    esac
    printf "\n"
  fi

  # ── Reset to base ──────────────────────────────────────────────────────────
  ghost_spinner_start "resetting to ${range}…"
  git reset --hard "${base_commit}"
  ghost_spinner_stop
  printf "\n"

  # ── Replay prompts ─────────────────────────────────────────────────────────
  for (( i=0; i<total; i++ )); do
    local prompt="${prompt_texts[$i]}"
    local num="$((i+1))"

    printf "%b[%d/%d]%b %s\n\n" \
      "${GH_PURPLE}${GH_BOLD}" "${num}" "${total}" "${GH_RESET}" "${prompt}"

    local ghost_args=(-m "$prompt" --agent "$agent")
    [ -n "$model" ] && ghost_args+=(--model "$model")

    if ! ghost commit "${ghost_args[@]}"; then
      gh_error "error: replay failed at step ${num}/${total}: ${prompt}"
      gh_error "  The branch has been partially replayed. Resolve the issue and continue manually."
      exit 1
    fi

    printf "\n"
  done

  # ── Summary ────────────────────────────────────────────────────────────────
  gh_success "  ✓ ghost rebase complete — ${total} commit(s) replayed with ${agent}"
  printf "\n"
}
